hw-4-2
js-tasks-ru/htmlcss-20221107_skitlzzzzz pull request #11
Opened 2022-12-03 21:03 UTC by yppix

2022-12-03 21:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 06:57 UTC, GSemikozov requested changes

2022-12-06 06:57 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    background-image: image-set(url("public/forest_1024.jpg") 1x,
в css так не делаем ` 1x`

2022-12-06 06:57 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    background-image: image-set(url("public/forest_1024.jpg") 1x,
поскольку с поддержкой оч плохо: https://caniuse.com/?search=image-set

2022-12-14 23:10 UTC, GSemikozov approved these changes

2022-12-14 23:10 UTC, merged