hw 3-2
js-tasks-ru/htmlcss-20221107_skitlzzzzz pull request #7
Opened 2022-11-26 22:24 UTC by yppix

2022-11-26 22:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-27 23:26 UTC, GSemikozov requested changes

2022-11-27 23:26 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные стили удалим из файла стилей данного блока

2022-11-28 23:15 UTC, GSemikozov approved these changes

2022-11-28 23:15 UTC, merged